### ISSUE TITLE
Hamburger menu || Hamburger menu is displayed to early

### ISSUE THREAD

**Issue by Knirkeli** [NoroffFEU/agency.noroff.dev#627]
The hamburger menu should not be used on 990px. It should only be for mobile devices.
Instead I suggest that the logo can be moved left on smaller screens to let the header scale better.

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/115043925/ab4f1754-4a58-486a-a273-ab3fe470adfd)

![Image](https://github.com/NoroffFEU/agency.noroff.dev/assets/115043925/293f6a5a-a309-46d4-8657-4a9ef5faa317)

**Comment by chrisbekk** [comment]
I would like to add that the log in button starts wrapping on <1240px which doesn't look right.

**Comment by YngvN** [comment]
This has been fixed along with the wrapping with #565

**Comment by Pgarza-dev** [comment]
Has the fix been merged to the main yet? I am still seeing the hamburger menu pop up at 990 px.

**Comment by Pgarza-dev** [comment]
I will remove myself as an assignee if your team is already on top of the task.

**Comment by bLangved** [comment]
There is allready an issue for this which I am working on #345:
 
https://github.com/NoroffFEU/agency.noroff.dev/issues/345

I will not try to sound harsh, but it is not efficient to raise issues for every minor thing that is being encountered. These "bugs" should rather be commented inside other issues that is allready working on that segment of code as a whole. 
ex. You can't have 10 people working on the header at once. It is guaranted to cause conflicts

**Comment by KarenJoo** [comment]
Hi @bLangved, does this mean you are working on responsiveness for the navbar including burger menu in issue #345 ? if so, thats great! I agree what you say here ^ and see some possibilites: 1) you can assign yourself to this issue 2) close this issue and update the #345 issue with more details ex mentioning burger/responsiveness in the issue name would be helpful when searching for existing issues in the project desktop board, or what do you reckon? :)

**Comment by bLangved** [comment]
@KarenJoo We will all probably get some collective information by the scrum masters very soon in regards to how we handle these conflicting issues. For now, I can assign  myself to header-related issues, sicne I am working on the overall header-design and functunality. 

I have created a new issue on this segment for simplicity: #672 Header - HTML, styling & script

**Comment by bLangved** [comment]
This is being fixed as a subtask in #672 . Closing this issue
